- name: Add create group *username*
  group:
    name: *username*

- name: Allow group *username* sudo without password  
  linefile:
    dest: /etc/sudoers
    state: present
    regexp: '^%*username*'
    line: '%*username* ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add user to group '*username*'
  user:
    name: *username*
    comment: "Service User for app Application"
    group: *username*
    append: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

       
